### ISSUE TITLE
about the current demo 

### ISSUE THREAD

**Issue by Liujingxiu23** [dtx525942103/VI-SVC#1]
Thank you for your great job and your sharing.
I have some questions:
1) For the demos in Bilibili, did you use the code you released, or you generated the demo using more complited model with hubert and  ppg used?
2) Have you did any experiments on cross-domain svc, I mean vc between speakers who only have speech data and speakers who only have singing dataset? 
3) You said "Big data [more and more wave] make things to be interesing!". What did you exactly mean? cross-languages? 
4) Could you share some results without background music?
Thank you again!

**Comment by dtx525942103** [comment]
> Thank you for your great job and your sharing. I have some questions:
> 
> 1. For the demos in Bilibili, did you use the code you released, or you generated the demo using more complited model with hubert and  ppg used?
> 2. Have you did any experiments on cross-domain svc, I mean vc between speakers who only have speech data and speakers who only have singing dataset?
> 3. You said "Big data [more and more wave] make things to be interesing!". What did you exactly mean? cross-languages?
> 4. Could you share some results without background music?
>    Thank you again!

1. now, the code haven't fully released.i still try to reorganize the code.
2. use speech data to train svc is easy; use  singing data to train vc is difficult; vc is easier than svc, but emotional vc is more difficult than svc.
3. use speech and  song of any speaker[with speaker embedding] as many as possible, don't care languages. data quality is important.
4. yes i can share.

**Comment by dtx525942103** [comment]
results without background music
https://www.bilibili.com/video/BV1BP4y1d7MM/
