### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by splinter21** [dtx525942103/VI-SVC#2]
1、有没有训过多人的？
我在最一开始看vits代码的时候，就好奇，为什么说话人信息（vits原作是id，这边是说话人vector）要加在后验编码器和decoder上，直到后来看到他基于这个做语音转换。
但是既然我们是通过pretrained hubert/ppg来输入source语义的话，不需要用vits的多说话人互相转音色功能，g的输入应该去掉才是？毕竟左边的后验+decoder分支应该是通用的vocoder功能吧，不需要跟说话人相关。
另外，如果是单人的话，说话人向量可能直接不需要了
2、DistributedBucketSampler最大调整到20s，不是很确定训练时显存占用如何。batch size不能开太大，否则比更小的音频时长，更容易爆显存，毕竟是在decoder前才做的slice。如果切得更碎一点，把20s降低，是不是更好？
3、看上去带nsf的decoder输入音高的功能还在开发中，先期待一发

**Comment by dtx525942103** [comment]
> 

1，这里一直都是训的多人；使用说话人vector是为了使用base模型finetune新发音人；加入g比不加g更容易收敛，不容是受数据不均衡的影响；
2，您的观点是正确的，我偷懒不想去切分数据了
3，是的，你发现了

**Comment by Liujingxiu23** [comment]
想请教下两位，有合适的 nsf-based vocoder 的开源代码吗？ 我一直没找到合适的呢。
