### ISSUE TITLE
hubert的shape和f0的shape对不上

### ISSUE THREAD

**Issue by splinter21** [dtx525942103/VI-SVC#4]
输入16kHz1通道的wav，hubert特征提取出来，时间维是377
按照https://github.com/dtx525942103/VI-SVC/blob/main/svc/prepare/preprocess_wave.py 把f0提取出来，时间维是757
如果把frame_period=1000 * self.hop / sr改为frame_period=2000 * self.hop / sr，时间维是379，还是比hubert时间维多2，这个是和计算f0时会padding有关吗？

**Comment by dtx525942103** [comment]
for hubert：[sample rate:16000][hop size:320] , output is [[1, 299:长度, 768:维度]]

i deal this by:
file = f"./{rootPath}/{spks}/{file}"
np_data = np.fromfile(file, dtype="float32")
np_data = np_data.reshape(-1, 768:维度)
np_data = np.repeat(np_data, 2, axis=0)
np.save(file, np_data)

in data_utils.py

len_min = min(len_phone, len_spec) # i know len_phone < len_spec
len_wav = len_min * self.hop_length
spec = spec[:, :len_min]
wav = wav[:, :len_wav]
phone = phone[:len_min, :]
pitch = pitch[:len_min]

the more length of 2, i haven't debug it, but f0 has more length of 1 than spec is f0 padding.

**Comment by splinter21** [comment]
比起np.repeat,hubert hop size调成16会更精细？

**Comment by Liujingxiu23** [comment]
请问hubert的输出是用来做什么的呢？ 我以为用fastasr输出PPG，替换phones就可以了。
![image](https://user-images.githubusercontent.com/49260794/190548299-304b60f9-e554-44bd-8497-5707fe5c2bdd.png)

**Comment by dtx525942103** [comment]
https://github.com/PlayVoice/VI-SVC/tree/main/svc_v1/prepare 可以看看这里，hubert是20ms一帧，做一次拷贝就可以替换phone了；现在没有nsf，应该会存在断音的情况；

**Comment by dtx525942103** [comment]
hubert是超大规模预训练模型，一般人玩不动，所以只有去适应他的参数
@Liujingxiu23 我以为用fastasr输出PPG，替换phones就可以了。svc代码里面的phones就是用的fastasr输出的PPG，由于他是C语言的，还不知道怎么整合；
